# resolver: lts-12.26
resolver: lts-19.3

ghc-options:
  vulkan-api:    -O2
  GLFW-b:        -O2
  bindings-GLFW: -O2
  entropy: -Wno-unsupported-calling-conventions
  monad-logger: -Wno-deprecations -Wno-missing-methods

allow-newer: true

extra-deps:
  - bindings-GLFW-3.3.2.0
  - GLFW-b-3.3.0.0
  - constraints-deriving-1.1.1.2
  - dimensions-2.1.1.0
  - easytensor-2.1.1.1
  - easytensor-vulkan-2.0.2.1
  - wavefront-0.7.1.3
  - vulkan-api-1.4.0.0
  - io-streams-haproxy-1.0.1.0
  
packages:
  - .