resolver: lts-12.26
# resolver: lts-16.5

ghc-options:
  vulkan-api:    -O2
  GLFW-b:        -O2
  bindings-GLFW: -O2
    
allow-newer: true

extra-deps:
  - bindings-GLFW-3.2.1.1
  - GLFW-b-3.2.1.0
  - constraints-deriving-1.1.1.0
  - dimensions-2.1.0.0
  - easytensor-2.1.0.0
  - easytensor-vulkan-2.0.2.0
  - wavefront-0.7.1.3
  - vulkan-api-1.3.0.0
  
packages:
  - .
